// RFC 5545 calendar output.
//
// Two things here matter more than the rest:
//   * UIDs are derived from the shift's date, so re-importing an updated file
//     overwrites the matching events in Google Calendar instead of stacking a
//     second copy on top of them.
//   * Times are written as floating local time (no Z, no TZID). A 06:00 shift
//     is 06:00 on the clock, which is what a roster means - writing UTC would
//     slide every shift by an hour at each DST changeover.

import {
  shiftStart, shiftEnd, shiftEndDateIso, shiftHours, isWorking, daysBetween,
} from './shift-engine.js';

const PRODID = '-//Lab Tools//Shift Rotation//EN';
const UID_DOMAIN = 'shifts.lab-tools';

function pad(n) {
  return String(n).padStart(2, '0');
}

function escapeText(value) {
  return String(value ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\;')
    .replace(/,/g, '\\,')
    .replace(/\r?\n/g, '\\n');
}

// Local wall-clock stamp with no timezone marker: 20260314T060000
function floatingStamp(date) {
  return `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}`
    + `T${pad(date.getHours())}${pad(date.getMinutes())}00`;
}

function dateStamp(iso) {
  return iso.replace(/-/g, '');
}

function utcStamp(date) {
  return `${date.getUTCFullYear()}${pad(date.getUTCMonth() + 1)}${pad(date.getUTCDate())}`
    + `T${pad(date.getUTCHours())}${pad(date.getUTCMinutes())}${pad(date.getUTCSeconds())}Z`;
}

// Content lines are limited to 75 octets; continuations start with a space.
// Folding by character never splits a multi-byte codepoint.
function foldLine(line) {
  if (line.length <= 74) return line;
  const parts = [line.slice(0, 74)];
  let rest = line.slice(74);
  while (rest.length > 73) {
    parts.push(` ${rest.slice(0, 73)}`);
    rest = rest.slice(73);
  }
  if (rest.length) parts.push(` ${rest}`);
  return parts.join('\r\n');
}

export function uidForDate(iso) {
  return `labtools-shift-${iso}@${UID_DOMAIN}`;
}

function alarmMinutesFor(shift, config) {
  if (shift.type.kind !== 'timed') return 0;
  const isNight = shift.code === 'N';
  const minutes = isNight ? config.nightAlarmMinutes : config.alarmMinutes;
  return Number.isFinite(Number(minutes)) ? Math.max(0, Math.round(Number(minutes))) : 0;
}

// Everything that would make an already-exported event look different. Used to
// decide whether SEQUENCE needs bumping on this export.
function signatureOf(event) {
  return [event.dtstart, event.dtend, event.allDay ? 'D' : 'T', event.summary, event.description, event.alarmMinutes].join('|');
}

function describeShift(shift, config) {
  const bits = [];
  if (shift.type.kind === 'timed') {
    bits.push(`${shift.type.start} - ${shift.type.end} (${shiftHours(shift.type)} h)`);
  }
  if (shift.overridden) bits.push('Manually adjusted in Lab Tools.');
  if (shift.note) bits.push(shift.note);
  bits.push('Generated by Lab Tools. Re-importing a newer file updates this event.');
  return bits.join('\n');
}

function eventForShift(shift, config) {
  const allDay = shift.type.kind === 'allday';
  const summary = shift.type.kind === 'timed'
    ? `${shift.type.label} Shift`
    : shift.type.label;

  return {
    uid: uidForDate(shift.date),
    date: shift.date,
    code: shift.code,
    allDay,
    dtstart: allDay ? dateStamp(shift.date) : floatingStamp(shiftStart(shift)),
    dtend: allDay ? dateStamp(shiftEndDateIso(shift)) : floatingStamp(shiftEnd(shift)),
    summary,
    description: describeShift(shift, config),
    location: config.location || '',
    alarmMinutes: alarmMinutesFor(shift, config),
  };
}

function renderEvent(event, sequence, dtstamp, cancelled = false) {
  const lines = [
    'BEGIN:VEVENT',
    `UID:${event.uid}`,
    `DTSTAMP:${dtstamp}`,
    event.allDay
      ? `DTSTART;VALUE=DATE:${event.dtstart}`
      : `DTSTART:${event.dtstart}`,
    event.allDay
      ? `DTEND;VALUE=DATE:${event.dtend}`
      : `DTEND:${event.dtend}`,
    `SUMMARY:${escapeText(cancelled ? `${event.summary} (cancelled)` : event.summary)}`,
    `SEQUENCE:${sequence}`,
    `STATUS:${cancelled ? 'CANCELLED' : 'CONFIRMED'}`,
    'TRANSP:OPAQUE',
    'CATEGORIES:Shift',
  ];

  if (!cancelled) {
    lines.push(`DESCRIPTION:${escapeText(event.description)}`);
    if (event.location) lines.push(`LOCATION:${escapeText(event.location)}`);
    if (event.alarmMinutes > 0) {
      lines.push(
        'BEGIN:VALARM',
        'ACTION:DISPLAY',
        `DESCRIPTION:${escapeText(`${event.summary} starts in ${event.alarmMinutes} minutes`)}`,
        `TRIGGER:-PT${event.alarmMinutes}M`,
        'END:VALARM',
      );
    }
  }

  lines.push('END:VEVENT');
  return lines;
}

/**
 * Build the .ics text for a range of shifts.
 *
 * @param shifts   every day in the exported range (off days included; they are skipped)
 * @param config   shift config, for alarm lead times and the calendar name
 * @param ledger   uid -> previously exported row, so changes bump SEQUENCE
 * @param range    { start, end } ISO bounds, used to scope cancellations
 * @returns { ics, ledgerRows, stats }
 */
export function buildCalendar({ shifts, config, ledger = {}, range, now = new Date() }) {
  const dtstamp = utcStamp(now);
  const exportedAt = now.getTime();

  const body = [];
  const ledgerRows = [];
  const stats = { created: 0, updated: 0, unchanged: 0, cancelled: 0, counts: {} };
  const liveUids = new Set();

  for (const shift of shifts) {
    if (!isWorking(shift)) continue;

    const event = eventForShift(shift, config);
    const signature = signatureOf(event);
    const previous = ledger[event.uid];
    liveUids.add(event.uid);
    stats.counts[shift.code] = (stats.counts[shift.code] || 0) + 1;

    let sequence;
    if (!previous) {
      sequence = 0;
      stats.created += 1;
    } else if (previous.signature !== signature || previous.cancelled) {
      // Google only accepts a revision whose SEQUENCE is higher than the one
      // it already holds, so a changed (or previously cancelled) shift steps up.
      sequence = (previous.sequence || 0) + 1;
      stats.updated += 1;
    } else {
      sequence = previous.sequence || 0;
      stats.unchanged += 1;
    }

    body.push(...renderEvent(event, sequence, dtstamp));
    ledgerRows.push({
      uid: event.uid,
      date: event.date,
      code: event.code,
      sequence,
      signature,
      summary: event.summary,
      allDay: event.allDay,
      dtstart: event.dtstart,
      dtend: event.dtend,
      cancelled: false,
      exportedAt,
    });
  }

  // A shift that was exported before but no longer exists (swapped away, turned
  // into a day off) needs an explicit cancellation, or it lingers in Google
  // Calendar forever. Only within the range being exported - dates outside it
  // simply weren't considered this time.
  for (const row of Object.values(ledger)) {
    if (row.cancelled || liveUids.has(row.uid)) continue;
    if (!range) continue;
    if (daysBetween(range.start, row.date) < 0) continue;
    if (daysBetween(row.date, range.end) < 0) continue;

    const sequence = (row.sequence || 0) + 1;
    body.push(...renderEvent(
      {
        uid: row.uid,
        allDay: row.allDay,
        dtstart: row.dtstart,
        dtend: row.dtend,
        summary: row.summary || 'Shift',
      },
      sequence,
      dtstamp,
      true,
    ));
    ledgerRows.push({ ...row, sequence, cancelled: true, exportedAt });
    stats.cancelled += 1;
  }

  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    `PRODID:${PRODID}`,
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${escapeText(config.calendarName || 'Lab Shifts')}`,
    ...body,
    'END:VCALENDAR',
  ];

  const ics = `${lines.map(foldLine).join('\r\n')}\r\n`;
  return { ics, ledgerRows, stats };
}

export function icsFilename(range) {
  return `lab-shifts-${range.start}-to-${range.end}.ics`;
}
